[package]
name = 'mfc/test-module'
version = '1.0.0'
description = 'Description for package'
 
[[module]]
name = 'test-module'
source = 'v1.0.0.wasm'
 
[[command]]
runner = 'wasi'
name = 'test-module'
module = 'test-module'

[command.annotations.wasi]
main-args = ["--verbose"]
env = ["RUST_LOG=debug"]